apiVersion: db.nils.gg/v1alpha1
kind: DatabaseInstance
metadata:
  name: mongodb
  namespace: staging
spec:
  type: mongodb
  uri: mongodb://127.0.0.1:27017
---
apiVersion: db.nils.gg/v1alpha1
kind: DatabaseUser
metadata:
  name: test
  namespace: staging
spec:
  databaseInstance: mongodb
  name: test
